---
title: "Appendix - Data 793"
author: "Cassandra Sperow"
date: "2023-11-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Appendix


```{r, obtain-packages}
# get working dir
getwd()

# Set the working directory to the location of your .rmd files
setwd("~/AU My Drive/001__DATA_793/R_dir_Corals_/analysis")

# Get a list of all .rmd files in the directory
rmd_files <- list.files(pattern = "\\.Rmd$", full.names = TRUE)

# Initialize an empty list to store the packages
loaded_packages <- character(0)

# Loop through each .rmd file
for (file in rmd_files) {
  # Read the content of the file
  content <- readLines(file)
  
  # Extract package names using regular expression
  package_lines <- grep("^(library|require)\\(", content, value = TRUE)
  
  # Extract package names from the lines
  packages <- gsub("^(library|require)\\((.*)\\)", "\\2", package_lines)
  
  # Remove leading and trailing whitespaces
  packages <- trimws(packages)
  
  # Add the packages to the list
  loaded_packages <- c(loaded_packages, packages)
}

# Remove any empty strings or NAs from the list
loaded_packages <- loaded_packages[loaded_packages != "" & !is.na(loaded_packages)]

# Display the unique list of loaded packages
cat("Loaded packages:", unique(loaded_packages), "\n")


```

