---
title: "CLR"
author: "Cassandra Sperow"
date: "2023-10-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
suppressMessages(library(tidyverse))
```

## CLR: Centered Log Ratio
Documentation: 
https://www.rdocumentation.org/packages/compositions/versions/2.0-6/topics/clr
- Based on importing raw counts
- Transforms compositional data, such as bacterial abundances, into centered log ratios
```{r}
# read in count-based data
read_csv("../output/rev_bacteria.csv") -> rev_bacteria
```


```{r}
# import library and transform to CLR
library(compositions)
clr(rev_bacteria[, -1]) -> clr_bac
```


```{r}
dim(clr_bac)
```

```{r}
class(clr_bac)
```

```{r}
clr_bac %>% as.data.frame() -> clr_bac_df
```

```{r}
write_csv(clr_bac_df, "../output/clr_bac_df.csv") # no sample column
```



### Clade C Subset 
```{r}
read_csv("../output/rev_coral_join.csv") %>% 
  filter(Clade == "C") -> clade_c_data
```


```{r}
# subset ASV columns for clr()
select(clade_c_data, starts_with("ASV")) -> clade_c_asvs
```


```{r}
library(compositions)
clr(clade_c_asvs) %>% 
  as.data.frame() -> clr_clade_c
```

```{r}
# check if any columns sum to 0
map(clr_clade_c, ~sum(.==0)) %>% 
  as.data.frame() %>% 
  pivot_longer(cols = everything()) %>% 
  filter(value == 0)
```

```{r}
write_csv(clr_clade_c, "../output/clr_clade_c.csv")
```

