---
title: "Clade C Correlation Plot"
author: "Cassandra Sperow"
date: "2023-11-12"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
suppressMessages(library(tidyverse))
```

## Clade C

```{r}
read_csv("../output/lr_data.csv") %>% 
  mutate(Clade = as.factor(Clade)) -> lr_data

head(lr_data)
```


## Correlation Matrix - Top 20
```{r}

cor_matrix_lr_data <- cor(lr_data[,-c(1,2)])

cor_matrix_lr_data[1:20,1:20]
```

```{r}
png(filename = "../plots/top20_corr_clade_c.png",
    width = 1200, height = 800)

library(corrplot)
top20_corr_clade_c <- corrplot(cor_matrix_lr_data[1:20, 1:20], 
                               method = "circle")

```



## Correlation Matrix - Top 50
- Anything over 50 gets small and hard to read
```{r}
png(filename = "../plots/top50_corr_clade_c.png",
    width = 1200, height = 800)

library(corrplot)
top50_corr_clade_c <- corrplot(cor_matrix_lr_data[1:50, 1:50], 
                               method = "circle")

```


# From Lasso Regression with Clade as Binary Outcome, ASV00013 was kept in the model

```{r}
# read in taxonomy table to see which bacterium this is
read_delim("../data/Files/16S_tax.txt") -> bac_tax


bac_tax %>% 
  filter(ASV == "ASV0013") %>% 
  pivot_longer(cols = everything())
```


```{r}
#plot(log(lr_data$ASV0013), lr_data$Clade)

ggplot(lr_data, aes( y = log(ASV0013), color = as.factor(Clade), fill = as.factor(Clade))) +
  geom_histogram() +
  coord_flip() +
  facet_wrap(~Clade) +
  xlab("Log of ASV0013 Counts") +
  ylab("")
```


```{r}
```


```{r}
```

